---
title: "About"
date: "2022-01-25"
output: html_fragment
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The ContDataSumViz Shiny app is a free R-based tool to help visualize 
continuous data (that has been QCed) in a standardized way without having to 
download any software programs to your computer. This Shiny app is linked to the
ContDataQC R package, which was developed by Erik W. Leppo from Tetra
Tech and is available on GitHub (<https://github.com/leppott/ContDataQC>). 
The table below provides an
overview of how the website is structured.

Development of the ContDataSumViz R tools has been funded by the United
States Environmental Protection Agency (EPA) Office of Research and
Development (ORD) as part of a larger project to establish Regional
Monitoring Networks (RMNs) for freshwater streams and inland lakes
(USEPA 2016, USEPA 2021; lead EPA scientist: Britta Bierwagen). The RMNs
are a volunteer, collaborative effort in which entities collect
long-term data at targeted sites to detect changes over time.

If you encounter problems with the Shiny app and/or have suggestions on
ways to further improve it, please email Erik
([Erik.Leppo\@tetratech.com](mailto:Erik.Leppo@tetratech.com){.email})
or post your comments on the ContDataSumViz GitHub page
(<https://github.com/leppott/ContDataSumViz/discussions>). This is an
open-source, collaborative effort and we welcome your feedback.

*Last updated 2022-01-25*
